### ISSUE TITLE
Addition of Object Detection Project

### ISSUE THREAD

**Issue by TechGeek3** [IOSD/IOSD-BPIT-Hacktoberfest-2022#129]
Object Detection Project using dnn model using video under AI and ML category.

**Comment by TechGeek3** [comment]
@KhushbooGupta2111 please assign me this.
Regards

**Comment by hiferli** [comment]
Thank you for adding your project :)

**Comment by TechGeek3** [comment]
This repo is excluded from hacktoberfest 😭
