### ISSUE TITLE
Regarding Data Structures related contributions

### ISSUE THREAD

**Issue by KhushbooGupta2111** [IOSD/IOSD-BPIT-Hacktoberfest-2022#18]
We are deleting DSA folder as it is does not abide by the Hacktoberfest values. Hence, we have created another folder Programming and Algorithms wherein you can add various algorithms in any programming language. 

Kindly make the changes @rishi2025 @abhishek2384 @ervaibhavkumar

**Comment by hiferli** [comment]
@ervaibhavkumar 
Can you shift your code from to this new folder?
Thanks

**Comment by hiferli** [comment]
Thank you Vaibhav for the contribution :)
