### ISSUE TITLE
SpringBoot Projects for HacktoberFest 2022

### ISSUE THREAD

**Issue by Parvezi123** [IOSD/IOSD-BPIT-Hacktoberfest-2022#21]
Hi @hiferli ,
Can we create SpringBoot Java-Based Projects for HacktoberFest 2022?
If Yes, Please let me know under which repository to create
Thanks

**Comment by KhushbooGupta2111** [comment]
Hey @Parvezi123 !
Yes definitely, you can contribute such projects. I have created a separate folder of backend inside Web Development. You can add there.

**Comment by hiferli** [comment]
Since the project is now submitted, I am closing the Issue.
In case you have any other issue(s), then raise another issue regarding the same 

Thanks
