### ISSUE TITLE
Please add the main function and leave comments for better understanding. Mention the constraints which you're talking about in a readme file.

### ISSUE THREAD

**Issue by hiferli** [IOSD/IOSD-BPIT-Hacktoberfest-2022#42]
Please add the main function and leave comments for better understanding. Mention the constraints which you're talking about in a readme file.

_Originally posted by @KhushbooGupta2111 in https://github.com/IOSD/IOSD-BPIT-Hacktoberfest-2022/issues/33#issuecomment-1272242758_

**Comment by hiferli** [comment]
Please do the changes
@puneetbawa

**Comment by KhushbooGupta2111** [comment]
@GGauravKKumar, please shift your code to programming and algorithm folder else it will be labled as invalid.
